#!/bin/sh
### BEGIN INIT INFO
# Provides:          irserver
# Required-Start:    $local_fs $remote_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: irserver
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="irserver"
NAME=irserver
DAEMON=/usr/bin/irserver
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

if [ -r /etc/default/$NAME ]; then
	. /etc/default/$NAME
fi

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions



do_start()
{
    start-stop-daemon --start --quiet -p $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
}
#
# Function that stops the daemon/service
#
do_stop()
{
        start-stop-daemon --stop --quiet -p $PIDFILE --oknodo --retry 5 --exec $DAEMON
        # -p $PIDFILE 
}

case "$1" in
  start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC using $DAEMON_ARGS" "$NAME"
        do_start
        case "$?" in
                0|1) log_end_msg 0 ;;
                2) [ log_end_msg 1 ;;
        esac
        ;;
  stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
                0|1) log_end_msg 0 ;;
                2) [ log_end_msg 1 ;;
        esac
        ;;
  restart|force-reload)
        do_stop
        do_start
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 3
        ;;
esac
