Document: xpleibd
Title: Debian xpleibd Manual
Author: <insert document author here>
Abstract: This manual describes what xpleibd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xpleibd/xpleibd.sgml.gz

Format: postscript
Files: /usr/share/doc/xpleibd/xpleibd.ps.gz

Format: text
Files: /usr/share/doc/xpleibd/xpleibd.text.gz

Format: HTML
Index: /usr/share/doc/xpleibd/html/index.html
Files: /usr/share/doc/xpleibd/html/*.html
