#!/bin/sh
while [ 1 ];

do
echo insert TUL and press any key..
read keypress

sudo dfu-programmer atmega32u4 erase; sudo dfu-programmer atmega32u4 flash main.hex; sudo dfu-programmer atmega32u4 reset

sleep 1
sudo lsusb -v -d 0x03eb: | grep iSerial
sleep 1
sudo lsusb -v -d 0x03eb: | grep iSerial

sudo lsusb -v -d 0x03eb: | grep iSerial | perl -lane 'print `date +%Y-%m-%d` . " $F[3]$F[-1]"' >> TUL.serial

done