#
# Makefile for xpl-eibd
#

#
# For LINUX, use the following
CCOPTS = -g -DLINUX -pedantic -Wall
LIBS = -g -lm 

# For UnixWare systems, use the following
# CCOPTS = -O2 -DUNIXWARE
# LIBS = -lnsl -lsocket -lm

#
# For Alpha/DEC OSF/Tru64
#
# CCOPTS = -O2 -DTRU64
# LIBS = -lm

# *******************************************************
# ******* No more customizations from here down *********
# *******************************************************
# top_srcdir = /home/markstaller/bcusdk.git/bcusdk-0.0.4

LDOPTS	= -O
CC	=	gcc $(CCOPTS)
LD	= 	gcc $(LDOPTS)

CMD_LIST = xpl-eibd

.c.o:	
	$(CC) -c $<

.o:
	$(LD) -o $@ $< ../xPL.a $(LIBS) 

.c:	
	$(CC) -c $<
	$(LD) -o $@ $< ../xPL.a $(LIBS)


all:	${CMD_LIST}

clean:
	rm -f *.o *.a core ${CMD_LIST}


rebuild: clean all





