Document: xpllib
Title: Debian xpllib Manual
Author: <insert document author here>
Abstract: This manual describes what xpllib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xpllib/xpllib.sgml.gz

Format: postscript
Files: /usr/share/doc/xpllib/xpllib.ps.gz

Format: text
Files: /usr/share/doc/xpllib/xpllib.text.gz

Format: HTML
Index: /usr/share/doc/xpllib/html/index.html
Files: /usr/share/doc/xpllib/html/*.html
